"""Añadir campo role a User

Revision ID: ee2edc2d0aab
Revises: d88ff6809ea7
Create Date: 2025-03-18 22:01:03.004375+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.utils.security import hash_password


# revision identifiers, used by Alembic.
revision: str = 'ee2edc2d0aab'
down_revision: Union[str, None] = 'd88ff6809ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    user_role_enum = sa.Enum('user', 'admin', 'player', name='userrole')
    user_role_enum.create(op.get_bind())  # Registro explícito del tipo Enum

    op.add_column('users', sa.Column('role', user_role_enum, nullable=False, server_default='user'))
    
    # Modificaciones adicionales generadas automáticamente
    op.alter_column('users', 'first_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'last_name', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'gender', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'country', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'phone_number', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'hashed_password', existing_type=sa.VARCHAR(), nullable=True)

    op.drop_column('users', 'is_player')
    op.drop_column('users', 'is_admin')

     # Hashear la contraseña del administrador
    hashed_password = hash_password("Cbp2025")

    # Crear el usuario administrador
    op.execute(f"""
        INSERT INTO users (email, first_name, last_name, gender, country, phone_number, hashed_password, role, is_verified, is_profile_complete)
        VALUES (
            'admin@cataloniablackballparty.com', 
            'Admin', 
            'Master', 
            'Otros', 
            'España', 
            '600000000', 
            '{hashed_password}', 
            'admin', 
            TRUE, 
            TRUE
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""

    # Agregar de nuevo las columnas eliminadas
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_player', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.alter_column('users', 'hashed_password', existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column('users', 'phone_number', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'country', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'gender', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'last_name', existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column('users', 'first_name', existing_type=sa.VARCHAR(), nullable=True)

    # Eliminar la columna y el tipo Enum
    op.drop_column('users', 'role')
    user_role_enum = sa.Enum('user', 'admin', 'player', name='userrole')
    user_role_enum.drop(op.get_bind())
    user_role_enum.drop(op.get_bind()) 
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('is_player', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
