"""Add country column to users

Revision ID: 3e11a9c3b06f
Revises: a85d9837c8cf
Create Date: 2025-03-14 09:54:35.288372+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e11a9c3b06f'
down_revision: Union[str, None] = 'a85d9837c8cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
